module.exports = {
  apps: [
    {
      name: 'ai-seo-ngrok',
      script: 'ngrok',
      // Point at Vite dev server (5173) which proxies API calls to backend (3000)
      args: 'http 5173 --url mothproof-choosy-irritable.ngrok-free.dev',
      exec_interpreter: 'none',
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'development',
      },
      watch: false,
      autorestart: true,
      max_restarts: 5,
      restart_delay: 3000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: 'logs/ngrok-err.log',
      out_file: 'logs/ngrok-out.log',
      merge_logs: true,
    },
    {
      name: 'ai-seo-backend',
      script: 'backend/index.ts',
      interpreter: 'npx',
      interpreter_args: 'tsx',
      env: {
        NODE_ENV: 'production',
      },
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      max_memory_restart: '1G',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: 'logs/err.log',
      out_file: 'logs/out.log',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      kill_timeout: 10000,
      wait_ready: true,
      listen_timeout: 10000,
    },
  ],
};
