name = "TDS Geo"
client_id = "a178c8740049e04eec663378b6e30ad8"
application_url = "https://16.192.29.174.nip.io"
embedded = true

[access_scopes]
scopes = "write_products,read_products,write_content,read_content,write_script_tags,read_script_tags,write_themes,read_themes"

[webhooks]
api_version = "2024-07"

[[webhooks.privacy]]
topic = "customers/redact"
address = "https://16.192.29.174.nip.io/api/webhooks/compliance"

[[webhooks.privacy]]
topic = "customers/data_request"
address = "https://16.192.29.174.nip.io/api/webhooks/compliance"

[[webhooks.privacy]]
topic = "shop/redact"
address = "https://16.192.29.174.nip.io/api/webhooks/compliance"

[auth]
redirect_urls = ["https://16.192.29.174.nip.io/api/auth/shopify/callback"]
