name = "Kivo Geo"
client_id = "a178c8740049e04eec663378b6e30ad8"
application_url = "https://ai.trafficdigitalsolutions.com"
embedded = true

[access_scopes]
scopes = "write_products,read_products,write_content,read_content,write_script_tags,read_script_tags,write_themes,read_themes"

[webhooks]
api_version = "2025-07"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://ai.trafficdigitalsolutions.com/api/webhooks/compliance"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "https://ai.trafficdigitalsolutions.com/api/webhooks/compliance"

[build]
automatically_update_urls_on_dev = true

[auth]
redirect_urls = ["https://ai.trafficdigitalsolutions.com/api/shopify/callback"]
