// ══════════════════════════════════════════════
// Enterprise Pipeline Routes Integration Tests
// Tests history, status, and run endpoints with
// mocked database and enterprise services
// ══════════════════════════════════════════════

import { describe, it, expect, vi, beforeEach } from 'vitest';

// ─── Mock JWT and bcrypt ─────────────────────
vi.mock('jsonwebtoken', () => ({
  default: {
    sign: vi.fn().mockReturnValue('test-jwt-token'),
    verify: vi.fn().mockReturnValue({
      userId: 'test-user-id',
      email: 'admin@test.com',
      role: 'admin',
      clientId: null, // admin users have no client scope
    }),
  }
}));

vi.mock('bcryptjs', () => ({
  default: {
    compare: vi.fn().mockResolvedValue(true),
    genSalt: vi.fn().mockResolvedValue('salt'),
    hash: vi.fn().mockResolvedValue('hashed-password'),
  }
}));

// ─── Mock Enterprise Services ────────────────
vi.mock('../../services/seoIntelligence', () => ({
  default: {
    initialize: vi.fn(),
    classifySearchIntent: vi.fn().mockResolvedValue({ intent: 'informational', confidence: 0.85 }),
    analyzeSERP: vi.fn().mockResolvedValue({ serpFeatures: [], entityLandscape: [] }),
    analyzeContentSEO: vi.fn().mockResolvedValue({ score: 72, suggestions: [] }),
    analyzeTopicalAuthority: vi.fn().mockResolvedValue({ score: 70, coverage: [] }),
  }
}));

vi.mock('../../services/factCheckService', () => ({
  default: {
    initialize: vi.fn(),
    verifyArticle: vi.fn().mockResolvedValue({
      overallConfidence: 0.95,
      requiresHumanReview: false,
      factChecks: [],
      citations: []
    }),
  }
}));

vi.mock('../../services/brandVoice', () => ({
  default: {
    initialize: vi.fn(),
    getContentGuidance: vi.fn().mockResolvedValue({ forbiddenPhrases: [], preferredTerminology: {} }),
    checkConsistency: vi.fn().mockResolvedValue({ score: 100, violations: [] }),
  }
}));

vi.mock('../../services/editorialWorkflow', () => ({
  default: {
    initialize: vi.fn(),
    createReviewAssignment: vi.fn().mockResolvedValue(undefined),
    advanceStatus: vi.fn().mockResolvedValue(undefined),
  }
}));

vi.mock('../../services/contentIntelligence', () => ({
  default: {
    initialize: vi.fn(),
    detectCannibalization: vi.fn().mockResolvedValue([]),
    findLinkingOpportunities: vi.fn().mockResolvedValue([]),
    extractEntities: vi.fn().mockResolvedValue([]),
  }
}));

vi.mock('../../services/aiEvaluation', () => ({
  default: {
    initialize: vi.fn(),
    evaluateContent: vi.fn().mockResolvedValue({ overall: 85, feedback: 'Good', dimensions: {} }),
    generateQualityReport: vi.fn().mockResolvedValue({
      qualityScore: { overall: 85, dimensions: {} },
      estimatedRankingPotential: 'high',
      actionableSteps: []
    }),
  }
}));

vi.mock('../../services/pexelsService', () => ({
  default: {
    initialize: vi.fn(),
    findImagesForArticle: vi.fn().mockResolvedValue({
      featuredImage: { url: 'https://images.pexels.com/test.jpg', altText: 'Test' },
      sectionImages: []
    }),
  }
}));

vi.mock('../../services/enterpriseSecurity', () => ({
  default: {
    initialize: vi.fn(),
    logAudit: vi.fn().mockResolvedValue(undefined),
  }
}));

vi.mock('../../services/costOptimization', () => ({
  default: {
    getInstance: vi.fn().mockReturnValue({
      initialize: vi.fn(),
      cheapThenPremium: vi.fn().mockResolvedValue(['Title', 'Content', 'Meta Title', 'Meta Desc']),
      close: vi.fn(),
    })
  }
}));

vi.mock('../../services/observability', () => ({
  default: {
    initialize: vi.fn(),
    startSpan: vi.fn().mockReturnValue({ id: 'span-1' }),
    endSpan: vi.fn(),
    close: vi.fn(),
  }
}));

vi.mock('../../services/openai', () => ({
  default: {
    initialize: vi.fn(),
    isMockMode: true,
    generateBlogPost: vi.fn().mockResolvedValue({
      title: 'Test Pipeline Article',
      content: '# Test\n\nContent generated by pipeline.',
      metaTitle: 'Test Meta',
      metaDescription: 'Test description.',
      tags: ['test'],
      metadata: { tokensIn: 50, tokensOut: 100, model: 'gpt-4o' }
    }),
    generateOutline: vi.fn().mockResolvedValue(['Intro', 'Body', 'Conclusion']),
  }
}));

// ─── Mock Pool Factory with Pipeline Runs ────

function createMockPoolWithPipelineData(): any {
  const pipelineRunsStore: Record<string, any[]> = {
    pipeline_runs: [
      {
        id: 'run-001',
        client_id: 'test-client-id',
        keyword: 'gutter cleaning tips',
        title: 'Complete Guide to Gutter Cleaning',
        success: true,
        stages: {
          serp_analysis: { intent: { intent: 'informational' } },
          generation: { title: 'Complete Guide to Gutter Cleaning', wordCount: 1200 },
          seo_analysis: { score: 85, suggestions: [] },
          fact_checking: { totalClaims: 3, overallConfidence: 0.95 },
          images: { featuredImage: 'https://example.com/img.jpg', sectionImages: 2 },
        },
        duration_ms: 3200,
        created_at: new Date('2026-05-31T12:00:00Z'),
      },
      {
        id: 'run-002',
        client_id: 'test-client-id',
        keyword: 'roof maintenance guide',
        title: 'Roof Maintenance: Essential Tips',
        success: true,
        stages: {
          serp_analysis: { intent: { intent: 'commercial' } },
          generation: { title: 'Roof Maintenance: Essential Tips', wordCount: 980 },
          seo_analysis: { score: 72, suggestions: ['Add more headings'] },
        },
        duration_ms: 2800,
        created_at: new Date('2026-05-31T11:00:00Z'),
      },
      {
        id: 'run-003',
        client_id: 'other-client-id',
        keyword: 'plumbing tips',
        title: null,
        success: false,
        stages: {
          serp_analysis: { error: 'SERP API timeout' },
        },
        duration_ms: 1500,
        created_at: new Date('2026-05-31T10:00:00Z'),
      },
    ],
  };

  let idCounter = 1;

  const query = async (text: string, params?: any[]) => {
    const tableMatch = text.match(/FROM\s+(?:(\w+))/i) ||
                       text.match(/INTO\s+(\w+)/i) ||
                       text.match(/UPDATE\s+(\w+)/i);
    const table = tableMatch ? tableMatch[1].toLowerCase() : '';

    if (text.trim().toUpperCase().startsWith('SELECT')) {
      if (text.includes('COUNT(*)') || text.includes('COUNT(')) {
        return { rows: [{ count: '0' }], rowCount: 1 };
      }

      if (table === 'pipeline_runs' && pipelineRunsStore.pipeline_runs) {
        // Handle LIMIT queries (history endpoint)
        const limitMatch = text.match(/LIMIT\s+(\d+)/i);
        const limit = limitMatch ? parseInt(limitMatch[1], 10) : 50;

        let filtered = [...pipelineRunsStore.pipeline_runs];

        // Filter by client_id if present in query
        if (params && params.length > 0 && text.includes('client_id = $1')) {
          filtered = filtered.filter(r => r.client_id === params[0]);
        }

        // Filter by id if present in query
        if (params && params.length > 0 && text.includes('WHERE id = $1')) {
          filtered = filtered.filter(r => r.id === params[0]);
        }

        // Sort by created_at DESC
        filtered.sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());

        return { rows: filtered.slice(0, limit), rowCount: filtered.length };
      }

      return { rows: [], rowCount: 0 };
    }

    if (text.trim().toUpperCase().startsWith('INSERT')) {
      const returningMatch = text.match(/RETURNING\s+(.+)/i);
      if (returningMatch) {
        const id = `run-new-${idCounter++}`;
        const newRow: Record<string, any> = { id };

        if (returningMatch[1].trim() === 'id, created_at') {
          newRow.created_at = new Date();
        }

        if (pipelineRunsStore[table]) {
          pipelineRunsStore[table].push(newRow);
        }

        return { rows: [newRow], rowCount: 1 };
      }
      if (pipelineRunsStore[table]) {
        pipelineRunsStore[table].push({ id: `new-${table}-${idCounter++}` });
      }
      return { rows: [], rowCount: 1 };
    }

    return { rows: [], rowCount: 0 };
  };

  return {
    query,
    connect: async () => ({
      query: async () => ({ rows: [], rowCount: 0 }),
      release: () => {}
    }),
    end: async () => {},
    on: vi.fn(),
  };
}

// ─── Helper: create request with user override ──

function createRequest(overrides: Record<string, any> = {}): any {
  return {
    body: {},
    query: {},
    params: {},
    headers: { authorization: 'Bearer test-jwt-token' },
    method: 'GET',
    originalUrl: '/api/pipeline/test',
    ...overrides,
    user: overrides.user || {
      userId: 'test-user-id',
      email: 'admin@test.com',
      role: 'admin',
      clientId: overrides.clientIdOverride !== undefined ? overrides.clientIdOverride : null,
    },
  };
}

function createResponse(): any {
  const res: Record<string, any> = {};
  res.status = (code: number) => {
    res.statusCode = code;
    return res;
  };
  res.json = (data: any) => {
    res.body = data;
    return res;
  };
  res.statusCode = 200;
  return res;
}

// ─── Route Stack Helpers ─────────────────────

function findRouteStack(routes: any): Array<{ path: string; methods: string[] }> {
  return (routes.stack || [])
    .filter((l: any) => l.route)
    .map((l: any) => ({
      path: l.route.path,
      methods: Object.keys(l.route.methods),
    }));
}

function findLayerByPath(routes: any, path: string): any | undefined {
  return (routes.stack || []).find((l: any) => l.route?.path === path);
}

// ─── Tests ────────────────────────────────────

describe('Enterprise Pipeline Routes', () => {
  let pool: any;
  let pipelineRoutes: any;

  beforeEach(async () => {
    pool = createMockPoolWithPipelineData();
    const mod = await import('../../routes/enterprisePipeline');
    pipelineRoutes = mod.createEnterprisePipelineRoutes(pool);
  });

  // ─── Route Registration ─────────────────────

  describe('route registration', () => {
    it('should create enterprise pipeline routes', () => {
      expect(pipelineRoutes).toBeDefined();
    });

    it('should register all expected pipeline endpoints', () => {
      const routes = findRouteStack(pipelineRoutes);
      const registeredPaths = routes.map(r => r.path);

      const expectedPaths = [
        '/run',
        '/optimized-generate',
        '/build-knowledge-graph',
        '/history/:clientId',
        '/status/:pipelineId',
      ];

      for (const path of expectedPaths) {
        expect(registeredPaths).toContain(path);
      }
    });

    it('should have correct HTTP methods on each endpoint', () => {
      const routes = findRouteStack(pipelineRoutes);
      const routeMap: Record<string, string[]> = {};

      for (const r of routes) {
        if (!routeMap[r.path]) routeMap[r.path] = [];
        routeMap[r.path].push(...r.methods);
      }

      expect(routeMap['/run']).toContain('post');
      expect(routeMap['/optimized-generate']).toContain('post');
      expect(routeMap['/build-knowledge-graph']).toContain('post');
      expect(routeMap['/history/:clientId']).toContain('get');
      expect(routeMap['/status/:pipelineId']).toContain('get');
    });
  });

  // ─── GET /history/:clientId ─────────────────

  describe('GET /history/:clientId', () => {
    it('should return pipeline history for a client', async () => {
      const req = createRequest({
        params: { clientId: 'test-client-id' },
      });
      const res = createResponse();

      // Find the history route handler and call it
      const layer = findLayerByPath(pipelineRoutes, '/history/:clientId');
      expect(layer).toBeDefined();

      // The middlewares (authenticate) are already mocked through JWT verify
      // Call the route handler directly
      await layer.route.stack[1].handle(req, res);

      expect(res.statusCode).toBe(200);
      expect(res.body.success).toBe(true);
      expect(res.body.data).toBeDefined();
      expect(res.body.data.length).toBe(2);
    });

    it('should format pipeline runs with stages array', async () => {
      const req = createRequest({
        params: { clientId: 'test-client-id' },
      });
      const res = createResponse();

      const layer = findLayerByPath(pipelineRoutes, '/history/:clientId');
      await layer.route.stack[1].handle(req, res);

      const firstRun = res.body.data[0];
      expect(firstRun.id).toBeDefined();
      expect(firstRun.keyword).toBeDefined();
      expect(firstRun.success).toBeDefined();
      expect(firstRun.duration).toBeDefined();
      expect(firstRun.stages).toBeInstanceOf(Array);
      expect(firstRun.created_at).toBeDefined();

      // Each stage should have name, status, and any stage data
      const firstStage = firstRun.stages[0];
      expect(firstStage.name).toBeDefined();
      expect(firstStage.status).toBeDefined();
    });

    it('should mark failed stages correctly', async () => {
      const req = createRequest({
        params: { clientId: 'other-client-id' },
      });
      const res = createResponse();

      const layer = findLayerByPath(pipelineRoutes, '/history/:clientId');
      await layer.route.stack[1].handle(req, res);

      expect(res.body.data.length).toBe(1);
      const failedRun = res.body.data[0];
      expect(failedRun.success).toBe(false);
      expect(failedRun.stages[0].status).toBe('failed');
      expect(failedRun.stages[0].error).toBeDefined();
    });

    it('should return empty data array for client with no runs', async () => {
      const req = createRequest({
        params: { clientId: 'nonexistent-client' },
      });
      const res = createResponse();

      const layer = findLayerByPath(pipelineRoutes, '/history/:clientId');
      await layer.route.stack[1].handle(req, res);

      expect(res.statusCode).toBe(200);
      expect(res.body.success).toBe(true);
      expect(res.body.data).toEqual([]);
    });

    it('should deny access to client-scoped user requesting another client history', async () => {
      // Simulate a user with clientId='my-client' trying to access 'other-client'
      const req = createRequest({
        params: { clientId: 'other-client' },
        user: {
          userId: 'client-user',
          email: 'client@test.com',
          role: 'client',
          clientId: 'my-client',
        },
        clientIdOverride: 'my-client',
      });
      const res = createResponse();

      const layer = findLayerByPath(pipelineRoutes, '/history/:clientId');
      await layer.route.stack[1].handle(req, res);

      expect(res.statusCode).toBe(403);
      expect(res.body.success).toBe(false);
      expect(res.body.error).toContain('Access denied');
    });

    it('should allow admin users to access any client history', async () => {
      const req = createRequest({
        params: { clientId: 'test-client-id' },
        user: {
          userId: 'admin-user',
          email: 'admin@test.com',
          role: 'admin',
          clientId: null,
        },
        clientIdOverride: null,
      });
      const res = createResponse();

      const layer = findLayerByPath(pipelineRoutes, '/history/:clientId');
      await layer.route.stack[1].handle(req, res);

      expect(res.statusCode).toBe(200);
      expect(res.body.success).toBe(true);
    });
  });

  // ─── GET /status/:pipelineId ────────────────

  describe('GET /status/:pipelineId', () => {
    it('should return a single pipeline run by ID', async () => {
      const req = createRequest({
        params: { pipelineId: 'run-001' },
      });
      const res = createResponse();

      const layer = findLayerByPath(pipelineRoutes, '/status/:pipelineId');
      await layer.route.stack[1].handle(req, res);

      expect(res.statusCode).toBe(200);
      expect(res.body.success).toBe(true);
      expect(res.body.data).toBeDefined();
      expect(res.body.data.id).toBe('run-001');
      expect(res.body.data.keyword).toBe('gutter cleaning tips');
      expect(res.body.data.title).toBe('Complete Guide to Gutter Cleaning');
      expect(res.body.data.stages).toBeInstanceOf(Array);
    });

    it('should include formatted duration string', async () => {
      const req = createRequest({
        params: { pipelineId: 'run-001' },
      });
      const res = createResponse();

      const layer = findLayerByPath(pipelineRoutes, '/status/:pipelineId');
      await layer.route.stack[1].handle(req, res);

      // 3200ms = 3.2s
      expect(res.body.data.duration).toBe('3.2s');
    });

    it('should return 404 for nonexistent pipeline run', async () => {
      const req = createRequest({
        params: { pipelineId: 'nonexistent-run' },
      });
      const res = createResponse();

      const layer = findLayerByPath(pipelineRoutes, '/status/:pipelineId');
      await layer.route.stack[1].handle(req, res);

      expect(res.statusCode).toBe(404);
      expect(res.body.success).toBe(false);
      expect(res.body.error).toContain('not found');
    });

    it('should include stages with correct status', async () => {
      const req = createRequest({
        params: { pipelineId: 'run-001' },
      });
      const res = createResponse();

      const layer = findLayerByPath(pipelineRoutes, '/status/:pipelineId');
      await layer.route.stack[1].handle(req, res);

      const stageNames = res.body.data.stages.map((s: any) => s.name);
      // All stages in run-001 are successful
      expect(stageNames).toContain('serp_analysis');
      expect(stageNames).toContain('generation');
      expect(stageNames).toContain('seo_analysis');
      expect(stageNames).toContain('fact_checking');
      expect(stageNames).toContain('images');

      // All stages should be 'completed'
      for (const stage of res.body.data.stages) {
        expect(stage.status).toBe('completed');
      }
    });
  });
});
