import { useState, useEffect } from 'react'

export default function ClientSettings() {
  const [saved, setSaved] = useState(false)

  const handleSave = (e: React.FormEvent) => {
    e.preventDefault()
    setSaved(true)
    setTimeout(() => setSaved(false), 3000)
  }

  return (
    <div className="tds-fade">
      {saved && <div className="tds-notice tds-notice-success">&#10003; Settings saved successfully.</div>}

      <form onSubmit={handleSave} className="tds-settings">
        <div className="tds-card" style={{ marginBottom: '24px', padding: '32px' }}>
          <h2 style={{ fontSize: '18px', fontWeight: 600, margin: '0 0 4px', color: 'var(--tds-text)' }}>Store Settings</h2>
          <p style={{ fontSize: '13px', color: 'var(--tds-text-tertiary)', margin: '0 0 24px' }}>
            Manage your TDS Geo integration settings.
          </p>

          <div className="tds-section-header">Connection</div>

          <div className="tds-field">
            <label>Store Domain</label>
            <input type="text" value="traffic-test.myshopify.com" disabled />
            <div className="tds-desc">Your Shopify store domain (read-only).</div>
          </div>

          <div className="tds-field tds-field-checkbox">
            <input type="checkbox" id="api_enabled" defaultChecked />
            <label htmlFor="api_enabled">API Enabled</label>
          </div>

          <div className="tds-field">
            <label>Default Article Status</label>
            <select defaultValue="draft">
              <option value="draft">Draft</option>
              <option value="pending">Pending Review</option>
              <option value="published">Published</option>
            </select>
            <div className="tds-desc">Default status for new articles generated by TDS Geo.</div>
          </div>

          <div className="tds-section-header" style={{ marginTop: '32px' }}>Publishing</div>

          <div className="tds-field tds-field-checkbox">
            <input type="checkbox" id="auto_publish" />
            <label htmlFor="auto_publish">Auto-publish approved articles</label>
          </div>

          <div className="tds-field">
            <label>Publish Frequency</label>
            <select defaultValue="weekly">
              <option value="daily">Daily</option>
              <option value="weekly">Weekly</option>
              <option value="monthly">Monthly</option>
              <option value="manual">Manual</option>
            </select>
          </div>

          <div style={{ marginTop: '32px' }}>
            <button type="submit" className="tds-btn tds-btn-primary">Save Settings</button>
          </div>
        </div>
      </form>
    </div>
  )
}
